name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.154.89
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update
            sudo apt install -y git docker.io
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu

            rm -rf devops-cicd-aws
            git clone https://github.com/Gogulwarsakshi/devops-cicd-aws.git
            cd devops-cicd-aws

            docker stop app || true
            docker rm app || true
            docker build -t app .
            docker run -d -p 80:5000 --name app app
